


class QuoteConstant():
    REQUEST_ACCEPTED = 'ACCEPTED'
    REQUEST_SUBMITTED = 'SUBMITTED'
    REQUEST_REJECTED = 'REJECTED'
    REQUEST_INPROGRESS = 'INPROGRESS'
    REQUEST_CANCELLED = 'CANCELLED'
    REQUEST_BOOKED = 'BOOKED'
    REQUEST_EXPIRED = 'EXPIRED'
    REQUEST_VIEWED = 'VIEWED'
    REQUEST_QUOTED = 'QUOTED'
    QUOTE_STATUS_OPEN = 'OPEN'
    QUOTE_STATUS_CLOSE = 'CLOSE'